# This file controls the configuration of our Netlify CMS UI+content structure
# 'branch' is the branch where all copy changes made in the CMS UI will be committed
# Netlify CMS docs: https://www.netlifycms.org/docs/intro/
#
# GitHub OAuth authentication is handed via a Vercel serverless function set up
# according to https://ironeko.com/posts/how-to-install-netlify-cms-on-vercel
# (using https://github.com/bericp1/netlify-cms-oauth-provider-node)
#
# It relies on environment variables in our Vercel project that point to the
# "TEMPLATE CMS" Github OAuth app
# (https://github.com/organizations/act-now-coalition/settings/applications/1789164).

backend:
  name: github
  repo: act-now-coalition/act-now-template
  branch: develop
  base_url: http://act-now-template.vercel.app/
  auth_endpoint: api/auth

# To use the CMS locally during development, run (on separate terminals):
#
#    yarn dev
#    yarn local-cms
#
# and then open http://localhost:3000/admin/index.html
local_backend: true

# Files uploaded through the CMS
media_folder: public/cms/media

# Path used to access the files in production
public_folder: /cms/media

collections:
  - name: site
    label: Site
    files:
      - name: settings
        label: Settings
        file: src/cms/content/settings.json
        fields:
          - name: siteName
            label: Site Name
          - name: siteUrl
            label: Site URL
          - name: siteLogo
            label: Site Logo
            hint: Logo image for the site
            widget: image
            allow_multiple: false
          - name: gaTrackingId
            label: Google Analytics Tracking ID
            hint: If you'd like to use Google Analytics, you can enter your tracking ID here.
            required: false
  - name: pages
    label: Pages
    files:
      - name: pages
        label: Pages
        file: src/cms/content/pages.json
        fields:
          - name: pages
            label: Pages
            widget: list
            fields:
              - name: pageId
                label: Page ID
              - name: microcopy
                label: Microcopy
                widget: list
                fields:
                  - name: microcopyId
                    label: Microcopy ID
                  - name: microcopyContent
                    widget: text
                    label: Microcopy Content
